appInsights:
  enabled: false
idam:
  s2s_url: http://localhost:4502
adminWeb:
  elastic_search_reindex_enabled: true
secrets:
  ccd:
    microservicekey-ccd-admin: AAAAAAAAAAAAAAAD
    ccd-admin-web-oauth2-client-secret: IIIIIIIIIIIIIIII
    AppInsightsInstrumentationKey: "some-key"
