apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  # Node specific vars
  USE_CSRF_PROTECTION: "true"
  SECURITY_REFERRER_POLICY: "origin"
  HPKP_MAX_AGE: "2592000"
  HPKP_SHA256S: "Set-proper-SHA256s"
  NODE_ENV: "production"
  UV_THREADPOOL_SIZE: "64"
  NODE_CONFIG_DIR: "./config"
  TS_BASE_URL: "./src/main"

  # Logging vars
  REFORM_TEAM: "ccd"
  REFORM_SERVICE_NAME: "admin-web"
  REFORM_ENVIRONMENT: "aat"

  # Application vars
  # IDAM
  IDAM_BASE_URL: "https://preprod-idamapi.reform.hmcts.net:3511"
  IDAM_S2S_URL: "http://rpe-service-auth-provider-saat.service.core-computer-saat.internal"
  IDAM_ADMIN_WEB_SERVICE_KEY: "${IDAM_SERVICE_KEY}"
  IDAM_SERVICE_NAME: "ccd_admin"
  IDAM_LOGOUT_URL: "https://idam.preprod.ccidam.reform.hmcts.net/login/logout"

  IDAM_OAUTH2_TOKEN_ENDPOINT: "https://preprod-idamapi.reform.hmcts.net:3511/oauth2/token"
  IDAM_OAUTH2_CLIENT_ID: "ccd_admin"
  IDAM_OAUTH2_AW_CLIENT_SECRET: "${OAUTH2_CLIENT_SECRET}"

  ADMINWEB_LOGIN_URL: "https://idam.preprod.ccidam.reform.hmcts.net/login"
  ADMINWEB_IMPORT_URL: "http://ccd-definition-store-api-saat.service.core-computer-saat.internal/import"
  ADMINWEB_JURISDICTIONS_URL: "http://ccd-definition-store-api-saat.service.core-computer-saat.internal/api/data/jurisdictions"
  ADMINWEB_USER_PROFILE_URL: "http://ccd-user-profile-api-saat.service.core-computer-saat.internal/users"
  ADMINWEB_SAVE_USER_PROFILE_URL: "http://ccd-user-profile-api-saat.service.core-computer-saat.internal/users/save"
  ADMINWEB_USER_ROLE_URL: "http://ccd-definition-store-api-saat.service.core-computer-saat.internal/api/user-role"
  ADMIN_ALL_USER_ROLES_URL: "http://ccd-definition-store-api-saat.service.core-computer-saat.internal/api/user-roles"

  # Storage Account
  STORAGEACCOUNT_PRIMARY_CONNECTION_STRING: "${STORAGEACCOUNT_PRIMARY_CONNECTION_STRING}"
  STORAGEACCOUNT_SECONDARY_CONNECTION_STRING: "${STORAGEACCOUNT_SECONDARY_CONNECTION_STRING}"
  STORAGE_CONTAINER_IMPORTS_CONTAINER_NAME: "ccd-admin-web-imports-saat"
