vault_section = "preprod"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
#idam_api_url = "https://idam-api.aat.platform.hmcts.net"
authentication_web_url = "https://idam.preprod.ccidam.reform.hmcts.net"
#authentication_web_url = "https://idam-web-public.aat.platform.hmcts.net"
capacity = "2"
asp_name = "ccd-admin-web-aat"
asp_rg = "ccd-admin-web-aat"
