idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
authentication_web_url = "https://idam.preprod.ccidam.reform.hmcts.net"
capacity = "2"
asp_name = "ccd-shared-demo"
asp_rg = "ccd-shared-demo"
